### ISSUE TITLE
It doesn't work for some reason

### ISSUE THREAD

**Issue by bulava92** [Bilan/connectlife-api-connector#25]
2024-04-02 14:10:01,671 DEBG 'mqtt' stdout output:
 PhpMqtt\Client\MqttClient->connectInternal() at /home/app/vendor/php-mqtt/client/src/MqttClient.php:123

2024-04-02 14:10:01,672 DEBG 'mqtt' stdout output:
 PhpMqtt\Client\MqttClient->connect() at /home/app/app/Providers/AppServiceProvider.php:29

2024-04-02 14:10:01,672 DEBG 'mqtt' stdout output:
 PhpMqtt\Client\MqttClient->connect() at /home/app/app/Providers/AppServiceProvider.php:29

2024-04-02 14:10:01,672 DEBG 'mqtt' stdout output:
 App\Providers\AppServiceProvider->App\Providers\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:908

2024-04-02 14:10:01,672 DEBG 'mqtt' stdout output:
 App\Providers\AppServiceProvider->App\Providers\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:908

2024-04-02 14:10:01,673 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795

2024-04-02 14:10:01,673 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795

2024-04-02 14:10:01,674 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957

2024-04-02 14:10:01,674 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957

2024-04-02 14:10:01,675 DEBG 'mqtt' stdout output:
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731

2024-04-02 14:10:01,675 DEBG 'mqtt' stdout output:
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731

2024-04-02 14:10:01,675 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942

2024-04-02 14:10:01,675 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942

2024-04-02 14:10:01,676 DEBG 'mqtt' stdout output:
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:1066

2024-04-02 14:10:01,676 DEBG 'mqtt' stdout output:
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:1066

2024-04-02 14:10:01,677 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolveClass() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:982

2024-04-02 14:10:01,677 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolveClass() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:982

2024-04-02 14:10:01,678 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolveDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:943
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:181
 Illuminate\Container\BoundMethod::addDependencyForCallParameter() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:124
 Illuminate\Container\BoundMethod::getMethodDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
 Illuminate\Container\BoundMethod::call() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:662
 Illuminate\Container\Container->call() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:211
 Illuminate\Console\Command->execute() at /home/app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->run() at /home/app/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /home/app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /home/app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
 Illuminate\Foundation\Console\Kernel->handle() at /home/app/artisan:35

2024-04-02 14:10:01,678 DEBG 'mqtt' stdout output:
 Illuminate\Container\Container->resolveDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:943
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:181
 Illuminate\Container\BoundMethod::addDependencyForCallParameter() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:124
 Illuminate\Container\BoundMethod::getMethodDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
 Illuminate\Container\BoundMethod::call() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:662
 Illuminate\Container\Container->call() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:211
 Illuminate\Console\Command->execute() at /home/app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->run() at /home/app/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /home/app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /home/app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
 Illuminate\Foundation\Console\Kernel->handle() at /home/app/artisan:35

2024-04-02 14:10:02,680 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-02 14:10:02,680 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by bulava92** [comment]
That's all you can catch. the login and password from the application are correct, MQTT works, I don't know what's going on

**Comment by bulava92** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:39:15] ERROR: Got unexpected response from the API: Service not enabled
Config OK
MQTT creds:  /  /  / no-ssl
MQTT configuration not found, running HTTP API only.
2024-04-02 14:39:16,892 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-02 14:39:16,892 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-02 14:39:16,893 INFO Included extra file "/home/app/docker-files/supervisord/_header.conf" during parsing
2024-04-02 14:39:16,893 INFO Included extra file "/home/app/docker-files/supervisord/_header.conf" during parsing
2024-04-02 14:39:16,893 INFO Included extra file "/home/app/docker-files/supervisord/_program-webapi.conf" during parsing
2024-04-02 14:39:16,893 INFO Included extra file "/home/app/docker-files/supervisord/_program-webapi.conf" during parsing
2024-04-02 14:39:16,904 INFO supervisord started with pid 168
2024-04-02 14:39:16,904 INFO supervisord started with pid 168
2024-04-02 14:39:17,909 INFO spawned: 'webapi' with pid 169
2024-04-02 14:39:17,909 INFO spawned: 'webapi' with pid 169
2024-04-02 14:39:18,788 DEBG 'webapi' stdout output:

   INFO  Server running on [http://0.0.0.0:8000].  


2024-04-02 14:39:18,788 DEBG 'webapi' stdout output:

   INFO  Server running on [http://0.0.0.0:8000].  


2024-04-02 14:39:18,789 DEBG 'webapi' stdout output:
  Press Ctrl+C to stop the server


2024-04-02 14:39:18,789 DEBG 'webapi' stdout output:
  Press Ctrl+C to stop the server


2024-04-02 14:39:19,791 INFO success: webapi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-02 14:39:19,791 INFO success: webapi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by Bilan** [comment]
Wrong credentials to MQTT server I think.

**Comment by bulava92** [comment]
> Wrong credentials to MQTT server I think.
Exactly correct, other services are connected

Tried to run through the console

pi@raspberrypi:~/connectlife-api-connector $ sudo docker run -it -p 8000:8000 -e CONNECTLIFE_LOGIN=$$$$ -e CONNECTLIFE_PASSWORD=$$$$-- -e LOG_LEVEL=info -e MQTT_HOST=192.168.3.172 -e MQTT_USER=pi  -e MQTT_PASSWORD=$$$$  -e MQTT_PORT=1883 -e MQTT_SSL=false ha-connectlife-addon /bin/ash -c 'php artisan app:mqtt-loop'
[2024-04-02 11:47:42] production.INFO: MQTT [192.168.3.172:1883] [connectlife-api] Connection with broker established successfully. {"host":"192.168.3.172","port":1883,"clientId":"connectlife-api","errorCode":"0x00"} 
[2024-04-02 11:47:42] production.INFO: Getting access token.  
[2024-04-02 11:47:42] production.INFO: Response ["{

  \"callId\": \"54e5f228f4b648c08cd56143521c3e27\",

  \"errorCode\": 403120,

  \"errorDetails\": \"Account temporarily locked out\",

  \"errorMessage\": \"Account Temporarily Locked Out\",

  \"apiVersion\": 2,

  \"statusCode\": 403,

  \"statusReason\": \"Forbidden\",

  \"time\": \"2024-04-02T11:47:42.905Z\"

}"] 
[2024-04-02 11:47:42] production.ERROR: Call to a member function body() on array {"exception":"[object] (Error(code: 0): Call to a member function body() on array at /home/app/app/Services/ConnectlifeApiService.php:83)
[stacktrace]
#0 /home/app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(397): App\\Services\\ConnectlifeApiService->App\\Services\\{closure}()
#1 /home/app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->remember()
#2 /home/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call()
#3 /home/app/app/Services/ConnectlifeApiService.php(62): Illuminate\\Support\\Facades\\Facade::__callStatic()
#4 /home/app/app/Services/ConnectlifeApiService.php(154): App\\Services\\ConnectlifeApiService->getAccessToken()
#5 /home/app/app/Services/ConnectlifeApiService.php(133): App\\Services\\ConnectlifeApiService->devices()
#6 /home/app/app/Services/MqttService.php(18): App\\Services\\ConnectlifeApiService->getOnlineAcDevices()
#7 [internal function]: App\\Services\\MqttService->__construct()
#8 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#9 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#10 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#11 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#12 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#13 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\\Foundation\\Application->make()
#14 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\\Container\\BoundMethod::addDependencyForCallParameter()
#15 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Container\\BoundMethod::getMethodDependencies()
#16 /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#18 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#19 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#20 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#21 /home/app/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#22 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#23 /home/app/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#24 /home/app/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#25 /home/app/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#26 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#27 /home/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#28 {main}
"} 

In ConnectlifeApiService.php line 83:
                                             
  Call to a member function body() on array

**Comment by Bilan** [comment]
Try changing connectlife password.

**Comment by bulava92** [comment]
> Try changing connectlife password.

Changed, unfortunately nothing has changed, the same log (

**Comment by Bilan** [comment]
Turn off the addon and try tomorrow. Maybe you hit some rate limits.

**Comment by bulava92** [comment]
It's the same today, the same mistakes (

**Comment by Bilan** [comment]
Are you able to login here:
https://api.connectlife.io/swagger/index.html
(authorize button)
?

**Comment by bulava92** [comment]
Yes, after that I immediately connected like a plugin, but the device was not created

2024-04-04 17:00:50,076 DEBG 'mqtt' stdout output:
[2024-04-04 14:00:50] production.INFO: Response ["{

  \"callId\": \"f1890e90bf6c41109a78be2f2ef7a586\",

  \"errorCode\": 0,

  \"apiVersion\": 2,

  \"statusCode\": 200,

  \"statusReason\": \"OK\",

  \"time\": \"2024-04-04T14:00:50.042Z\",

...

2024-04-04 17:00:51,543 DEBG 'mqtt' stdout output:
[2024-04-04 14:00:51] production.INFO: Response ["[]"] 

2024-04-04 17:00:51,543 DEBG 'mqtt' stdout output:
[2024-04-04 14:00:51] production.INFO: Response ["[]"] 

2024-04-04 17:00:51,543 DEBG 'mqtt' stdout output:
Home Assistant discovery created.

2024-04-04 17:00:51,543 DEBG 'mqtt' stdout output:
Home Assistant discovery created.

2024-04-04 17:00:51,544 DEBG 'mqtt' stdout output:
Home Assistant subscribes created.

2024-04-04 17:00:51,544 DEBG 'mqtt' stdout output:
Home Assistant subscribes created.

2024-04-04 17:00:51,619 DEBG 'mqtt' stdout output:
[2024-04-04 14:00:51] production.INFO: Response ["[]"] 

2024-04-04 17:00:51,619 DEBG 'mqtt' stdout output:
[2024-04-04 14:00:51] production.INFO: Response ["[]"] 

2024-04-04 17:01:51,843 DEBG 'mqtt' stdout output:
[2024-04-04 14:01:51] production.INFO: Response ["[]"] 

2024-04-04 17:01:51,843 DEBG 'mqtt' stdout output:
[2024-04-04 14:01:51] production.INFO: Response ["[]"] 

2024-04-04 17:02:52,308 DEBG 'mqtt' stdout output:
[2024-04-04 14:02:52] production.INFO: Response ["[]"] 

2024-04-04 17:02:52,308 DEBG 'mqtt' stdout output:
[2024-04-04 14:02:52] production.INFO: Response ["[]"] 

2024-04-04 17:03:52,595 DEBG 'mqtt' stdout output:
[2024-04-04 14:03:52] production.INFO: Response ["[]"] 

2024-04-04 17:03:52,595 DEBG 'mqtt' stdout output:
[2024-04-04 14:03:52] production.INFO: Response ["[]"] 

2024-04-04 17:04:52,759 DEBG 'mqtt' stdout output:
[2024-04-04 14:04:52] production.INFO: Response ["[]"] 

2024-04-04 17:04:52,759 DEBG 'mqtt' stdout output:
[2024-04-04 14:04:52] production.INFO: Response ["[]"]

**Comment by bulava92** [comment]
My air conditioner is connected to the network and controlled through the "connect life" application, but it is not visible through this plugin (

**Comment by Bilan** [comment]
Paste your logs after add-on start please.

**Comment by bulava92** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Config OK
MQTT creds: 192.168.3.172 / pi / 1883 / no-ssl
HTTP API disabled, running MQTT client only.
2024-04-05 18:21:06,284 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-05 18:21:06,284 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-04-05 18:21:06,285 INFO Included extra file "/home/app/docker-files/supervisord/_header.conf" during parsing
2024-04-05 18:21:06,285 INFO Included extra file "/home/app/docker-files/supervisord/_header.conf" during parsing
2024-04-05 18:21:06,285 INFO Included extra file "/home/app/docker-files/supervisord/_program-mqtt.conf" during parsing
2024-04-05 18:21:06,285 INFO Included extra file "/home/app/docker-files/supervisord/_program-mqtt.conf" during parsing
2024-04-05 18:21:06,296 INFO supervisord started with pid 142
2024-04-05 18:21:06,296 INFO supervisord started with pid 142
2024-04-05 18:21:07,301 INFO spawned: 'mqtt' with pid 143
2024-04-05 18:21:07,301 INFO spawned: 'mqtt' with pid 143
2024-04-05 18:21:07,660 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:07] production.INFO: MQTT [192.168.3.172:1883] [connectlife-api] Connection with broker established successfully. {"host":"192.168.3.172","port":1883,"clientId":"connectlife-api","errorCode":"0x00"} 

2024-04-05 18:21:07,660 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:07] production.INFO: MQTT [192.168.3.172:1883] [connectlife-api] Connection with broker established successfully. {"host":"192.168.3.172","port":1883,"clientId":"connectlife-api","errorCode":"0x00"} 

2024-04-05 18:21:07,673 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:07] production.INFO: Getting access token.  

2024-04-05 18:21:07,673 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:07] production.INFO: Getting access token.  

   \"email\": \"secret@gmail.com\",

    \"photoURL\": \"https://lh3.googleusercontent.com/a/secret=s96-c?sz=500\",

    \"thumbnailURL\": \"https://lh3.googleusercontent.com/a/secret=s96-c?sz=50\"

  },

  \"registered\": \"2024-04-02T16:08:32.646Z\",

  \"socialProviders\": \"googleplus,site\",

  \"verified\": \"2024-04-02T16:08:24.766Z\",

  \"verifiedTimestamp\": 1712074104766,

  \"newUser\": false,

  \"sessionInfo\": {

    \"cookieName\": \"secret-_A\",

    \"cookieValue\": \"st2.s.AcbHicdg9w.secret-d1gHi15SjL2k0-secret-secret-m2ATw-HLdOmf_Tjw.sc3\"

  }

}"] 

2024-04-05 18:21:08,304 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:08] production.INFO: Response ["{

  \"callId\": \"secret\",

  \"errorCode\": 0,

  \"apiVersion\": 2,

  \"statusCode\": 200,

  \"statusReason\": \"OK\",

  \"time\": \"2024-04-05T15:21:08.270Z\",

  \"id_token\": \"secret.secret-secret-9z0N-secret-secret\"

}"] 

2024-04-05 18:21:08,304 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:08] production.INFO: Response ["{

  \"callId\": \"secret\",

  \"errorCode\": 0,

  \"apiVersion\": 2,

  \"statusCode\": 200,

  \"statusReason\": \"OK\",

  \"time\": \"2024-04-05T15:21:08.270Z\",

  \"id_token\": \"secret.secret-secret-9z0N-secret-secret\"

}"] 

2024-04-05 18:21:08,305 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-05 18:21:08,305 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-04-05 18:21:09,143 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["{\"resultCode\":0,\"code\":\"secret\",\"redirect_uri\":\"https://api.connectlife.io/swagger/oauth2-redirect.html\",\"state\":null}"] 

2024-04-05 18:21:09,143 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["{\"resultCode\":0,\"code\":\"secret\",\"redirect_uri\":\"https://api.connectlife.io/swagger/oauth2-redirect.html\",\"state\":null}"] 

2024-04-05 18:21:09,214 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["{\"resultCode\":0,\"access_token\":\"secret-secret\",\"token_type\":\"Bearer\",\"expires_in\":1440,\"scope\":\"\",\"refresh_token\":\"secret-secret-secret\"}"] 

2024-04-05 18:21:09,214 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["{\"resultCode\":0,\"access_token\":\"secret-secret\",\"token_type\":\"Bearer\",\"expires_in\":1440,\"scope\":\"\",\"refresh_token\":\"secret"}"] 

2024-04-05 18:21:09,555 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["[]"] 

2024-04-05 18:21:09,555 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["[]"] 

2024-04-05 18:21:09,557 DEBG 'mqtt' stdout output:
Home Assistant discovery created.
Home Assistant subscribes created.

2024-04-05 18:21:09,557 DEBG 'mqtt' stdout output:
Home Assistant discovery created.
Home Assistant subscribes created.

2024-04-05 18:21:09,632 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["[]"] 

2024-04-05 18:21:09,632 DEBG 'mqtt' stdout output:
[2024-04-05 15:21:09] production.INFO: Response ["[]"]

**Comment by bulava92** [comment]
Is there any information, can it work for me?

**Comment by Bilan** [comment]
I have no idea. I can debug it for you but I will need your credentials.

**Comment by martin131** [comment]
same problem on my installation

**Comment by bulava92** [comment]
> I have no idea. I can debug it for you but I will need your credentials.

Thank you! I sent your credentials to your email

**Comment by Bilan** [comment]
@bulava92 I logged in to your account in the connectlife iOS app (https://apps.apple.com/pl/app/connectlife/id1519398796). The app forced me to select my region. I did that and no devices were added to your account, empty. I think you have to use VPN because the problem is related with your region.

**Comment by moskovskiy82** [comment]
> @bulava92 I logged in to your account in the connectlife iOS app (https://apps.apple.com/pl/app/connectlife/id1519398796). The app forced me to select my region. I did that and no devices were added to your account, empty. I think you have to use VPN because the problem is related with your region.

Can confirm that. Guess there are several datacenters. Couldn't even log in to swagger when it was up.
So for the integration to work you have to change the region to some EU country.
For some reason i couldn't do that on the android app (region was forced). So i had to use an iphone.

**Comment by Bilan** [comment]
Thanks for sharing this information.

**Comment by Monacoslo** [comment]
The only difference is China and Russia. All other countries should work the same way

**Comment by iTigere** [comment]
I can't turn on the split. all other functions are ok

**Comment by iTigere** [comment]
How do I change the region in the app?

**Comment by iTigere** [comment]
I tried uninstalling and reinstalling but it gives me the following error. Suggestions?

The add-on could not be installed
The command '/bin/ash -o pipefail -c composer install --no-interaction --no-dev' returned a non-zero code: 2

**Comment by KostaMadorsky** [comment]
> Are you able to login here:
> https://api.connectlife.io/swagger/index.html
> (authorize button)
> ?

Have they just killed their API??
I'm getting the following when I try to access swagger over the URL 

"{"error_msg":"404 Route Not Found"}"


It also started giving me 502s in the integration in HA when I try to reload it...

**Comment by sashavod** [comment]
just bought washing machine. successfully added to mobile application. but while adding to integration in HA I got the error: Invalid authentication. Also I cannot open https://api.connectlife.io/swagger/index.html  : "{"error_msg":"404 Route Not Found"}". Any solutions?
