### ISSUE TITLE
Unable to control one out of two AC

### ISSUE THREAD

**Issue by chowhi123** [bilan/connectlife-api-connector#46]
First of thank you for developing such an awesome integration. Only 15 issues on this project proves how superior this app has been. 

I have small problem that makes me unable to control that somebody might have a better idea on how to fix this. I can't control it, but it seems like it is getting status report back via API. Below is log for when I try to change the device mode.

Thank you!

[2024-06-26 19:18:50] production.INFO: Mqtt: received a  on [pu000088650051000200030003000000887ddb7db1b/ac/mode/set] off  
[2024-06-26 19:18:50] production.ERROR: MQTT [core-mosquitto:1883] [connectlife-api] Subscriber callback threw exception for published message on topic [pu000088650051000200030003000000887ddb7db1b/ac/mode/set]. {"host":"core-mosquitto","port":1883,"clientId":"connectlife-api","topic":"pu000088650051000200030003000000887ddb7db1b/ac/mode/set","message":"off","exception":"[object] (ErrorException(code: 0): Undefined array key \"\" at /home/app/app/Services/AcDevice.php:104)
[stacktrace]
#0 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/app/app/Services/AcDevice.php(104): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/app/app/Services/MqttService.php(91): App\\Services\\AcDevice->toConnectLifeApiPropertiesArray()
#3 /home/app/app/Services/MqttService.php(81): App\\Services\\MqttService->updateAcDevice()
#4 /home/app/app/Services/MqttService.php(62): App\\Services\\MqttService->reactToMessageOnTopic()
#5 [internal function]: App\\Services\\MqttService->App\\Services\\{closure}()
#6 /home/app/vendor/php-mqtt/client/src/MqttClient.php(899): call_user_func()
#7 /home/app/vendor/php-mqtt/client/src/MqttClient.php(729): PhpMqtt\\Client\\MqttClient->deliverPublishedMessage()
#8 /home/app/vendor/php-mqtt/client/src/MqttClient.php(686): PhpMqtt\\Client\\MqttClient->handleMessage()
#9 /home/app/vendor/php-mqtt/client/src/MqttClient.php(640): PhpMqtt\\Client\\MqttClient->processMessageBuffer()
#10 /home/app/app/Console/Commands/MqttLoop.php(49): PhpMqtt\\Client\\MqttClient->loopOnce()
#11 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\MqttLoop->handle()
#12 /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#16 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#17 /home/app/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#18 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#19 /home/app/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#20 /home/app/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /home/app/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#22 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#23 /home/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#24 {main}
"}

**Comment by chowhi123** [comment]
Mine started working fine on both device. One device must have been rate limited for unknown reason.
