### ISSUE TITLE
I have a problem with api permissions

### ISSUE THREAD

**Issue by superzu** [bilan/connectlife-api-connector#50]
I installed the component. I am sure of the passwords for both the mqtt host and the connectlife app. I attach log. From the error it seems that the account is not enabled for the API service

-----------------------------------------------------------

 Add-on: Connectlife API proxy & MQTT Add-on
 Integrates Connectlife AC devices with Home Assistant via MQTT and provides an HTTP API
-----------------------------------------------------------
 Add-on version: 2.1.11
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.7.1
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Config OK
MQTT creds: 10.10.10.101 / mqtt-user / 1883 / no-ssl
2024-07-10 11:25:47,161 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-07-10 11:25:47,162 INFO Included extra file "/home/app/docker-files/supervisord/_header.conf" during parsing
2024-07-10 11:25:47,162 INFO Included extra file "/home/app/docker-files/supervisord/_program-webapi.conf" during parsing
2024-07-10 11:25:47,162 INFO Included extra file "/home/app/docker-files/supervisord/_program-mqtt.conf" during parsing
2024-07-10 11:25:47,167 INFO supervisord started with pid 214
2024-07-10 11:25:48,170 INFO spawned: 'mqtt' with pid 215
2024-07-10 11:25:48,174 INFO spawned: 'webapi' with pid 216
[2024-07-10 09:23:36] production.INFO: Response ["{

  \"callId\": \"927e83b24728c283f1e995de27aed567\",

  \"errorCode\": 403120,

  \"errorDetails\": \"Account temporarily locked out\",

  \"errorMessage\": \"Account Temporarily Locked Out\",

  \"apiVersion\": 2,

  \"statusCode\": 403,

  \"statusReason\": \"Forbidden\",

  \"time\": \"2024-07-10T09:25:48.721Z\"

}"] 
[2024-07-10 09:25:48] production.ERROR: Cannot login to Connectlife. Response: {"callId":"927e83b24728c283f1e995de27aed567","errorCode":403120,"errorDetails":"Account temporarily locked out","errorMessage":"Account Temporarily Locked Out","apiVersion":2,"statusCode":403,"statusReason":"Forbidden","time":"2024-07-10T09:25:48.721Z"} {"exception":"[object] (Exception(code: 0): Cannot login to Connectlife. Response: {\"callId\":\"927e83b24728c283f1e995de27aed567\",\"errorCode\":403120,\"errorDetails\":\"Account temporarily locked out\",\"errorMessage\":\"Account Temporarily Locked Out\",\"apiVersion\":2,\"statusCode\":403,\"statusReason\":\"Forbidden\",\"time\":\"2024-07-10T09:25:48.721Z\"} at /home/app/app/Services/ConnectlifeApiService.php:83)
[stacktrace]
#0 /home/app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(397): App\\Services\\ConnectlifeApiService->App\\Services\\{closure}()
#1 /home/app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->remember()
#2 /home/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call()
#3 /home/app/app/Services/ConnectlifeApiService.php(62): Illuminate\\Support\\Facades\\Facade::__callStatic()
#4 /home/app/app/Services/ConnectlifeApiService.php(154): App\\Services\\ConnectlifeApiService->getAccessToken()
#5 /home/app/app/Services/ConnectlifeApiService.php(133): App\\Services\\ConnectlifeApiService->devices()
#6 /home/app/app/Services/MqttService.php(18): App\\Services\\ConnectlifeApiService->getOnlineAcDevices()
#7 [internal function]: App\\Services\\MqttService->__construct()
#8 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#9 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#10 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()
#11 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#12 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()
#13 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\\Foundation\\Application->make()
#14 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\\Container\\BoundMethod::addDependencyForCallParameter()
#15 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Container\\BoundMethod::getMethodDependencies()
#16 /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#18 /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#19 /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#20 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#21 /home/app/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#22 /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#23 /home/app/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#24 /home/app/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#25 /home/app/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#26 /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#27 /home/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#28 {main}
"} 

In ConnectlifeApiService.php line 83:
                                                                               
  [Exception]                                                                  
  Cannot login to Connectlife. Response: {"callId":"927e83b24728c283f1e995de2  
  7aed567","errorCode":403120,"errorDetails":"Account temporarily locked out"  
  ,"errorMessage":"Account Temporarily Locked Out","apiVersion":2,"statusCode  
  ":403,"statusReason":"Forbidden","time":"2024-07-10T09:25:48.721Z"}          
                                                                               

Exception trace:
  at /home/app/app/Services/ConnectlifeApiService.php:83
 App\Services\ConnectlifeApiService->App\Services\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:397
 Illuminate\Cache\Repository->remember() at /home/app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:429
 Illuminate\Cache\CacheManager->__call() at /home/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355
 Illuminate\Support\Facades\Facade::__callStatic() at /home/app/app/Services/ConnectlifeApiService.php:62
 App\Services\ConnectlifeApiService->getAccessToken() at /home/app/app/Services/ConnectlifeApiService.php:154
 App\Services\ConnectlifeApiService->devices() at /home/app/app/Services/ConnectlifeApiService.php:133
 App\Services\ConnectlifeApiService->getOnlineAcDevices() at /home/app/app/Services/MqttService.php:18
 App\Services\MqttService->__construct() at n/a:n/a
 ReflectionClass->newInstanceArgs() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:952
 Illuminate\Container\Container->build() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
 Illuminate\Container\Container->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:957
 Illuminate\Foundation\Application->resolve() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
 Illuminate\Container\Container->make() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:942
 Illuminate\Foundation\Application->make() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:181
 Illuminate\Container\BoundMethod::addDependencyForCallParameter() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:124
 Illuminate\Container\BoundMethod::getMethodDependencies() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
 Illuminate\Container\Util::unwrapIfClosure() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:35
 Illuminate\Container\BoundMethod::call() at /home/app/vendor/laravel/framework/src/Illuminate/Container/Container.php:662
 Illuminate\Container\Container->call() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:211
 Illuminate\Console\Command->execute() at /home/app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /home/app/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->run() at /home/app/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /home/app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /home/app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /home/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:201
 Illuminate\Foundation\Console\Kernel->handle() at /home/app/artisan:35

   INFO  Server running on [http://0.0.0.0:8000].  

  Press Ctrl+C to stop the server

2024-07-10 11:25:49,955 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-10 11:25:49,955 INFO success: webapi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by bilan** [comment]
Hi, 
try changing Connectlife password.

**Comment by AlexDezhnev** [comment]
Same Problem. Changed Connectlife password 3 times

In ConnectlifeApiService.php line 83:
                                                                               
  [Exception]                                                                  
  Cannot login to Connectlife. Response: {"callId":"30301b1fac409b1a542bbd413  
  480c7f8","errorCode":403120,"errorDetails":"Account temporarily locked out"  
  ,"errorMessage":"Account Temporarily Locked Out","apiVersion":2,"statusCode  
  ":403,"statusReason":"Forbidden","time":"2024-07-26T05:29:03.484Z"}

**Comment by basalisco** [comment]
> Same Problem. Changed Connectlife password 3 times
> 
> In ConnectlifeApiService.php line 83:
> 
> [Exception] Cannot login to Connectlife. Response: {"callId":"30301b1fac409b1a542bbd413 480c7f8","errorCode":403120,"errorDetails":"Account temporarily locked out" ,"errorMessage":"Account Temporarily Locked Out","apiVersion":2,"statusCode ":403,"statusReason":"Forbidden","time":"2024-07-26T05:29:03.484Z"}


when disable http API

```
In ConnectlifeApiService.php line 83:
  [Exception]                                                                  
  Cannot login to Connectlife. Response: {"callId":"5ed8e125f1014d578c3137068  
  efd2c04","errorCode":403048,"errorDetails":"Api Rate limit exceeded","error  
  Message":"Api rate limit exceeded","apiVersion":2,"statusCode":403,"statusR  
  eason":"Forbidden","time":"2024-11-17T18:28:37.356Z"} 
```

**Comment by ajimenezdev** [comment]
Sane issue stayed suddenly after working fine for a couple of months 

This is the error shown on restarting:

```

2025-03-29 00:55:34,497 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
In ConnectlifeApiService.php line 83:
  [Exception]                                                                  
  Cannot login to Connectlife. Response: {"callId":"60f13f5bbe1843b48ef5f76b9  
  f90613b","errorCode":403048,"errorDetails":"Api Rate limit exceeded","error  
  Message":"Api rate limit exceeded","apiVersion":2,"statusCode":403,"statusR  
  eason":"Forbidden","time":"2025-03-28T23:55:34.418Z"}

```

**Comment by bilan** [comment]
> Same issue stayed suddenly after working fine for a couple of months 
> 
> This is the error shown on restarting:
> 
> ```
> 
> 2025-03-29 00:55:34,497 INFO success: mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> In ConnectlifeApiService.php line 83:
>   [Exception]                                                                  
>   Cannot login to Connectlife. Response: {"callId":"60f13f5bbe1843b48ef5f76b9  
>   f90613b","errorCode":403048,"errorDetails":"Api Rate limit exceeded","error  
>   Message":"Api rate limit exceeded","apiVersion":2,"statusCode":403,"statusR  
>   eason":"Forbidden","time":"2025-03-28T23:55:34.418Z"}
> 
> ```

You have to login to ConnectLife app and accept new terms I think.
